name: Publish Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: ghcr.io
          name: ghcr.io/mspolermo/top-app/client
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"
          dockerfile: client/Dockerfile
          context: client

      - name: Publish server image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: ghcr.io
          name: ghcr.io/mspolermo/top-app/server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"
          dockerfile: server/Dockerfile
          context: server